### ISSUE TITLE
Automatically rebuild images when detecting "critical" CVEs

### ISSUE THREAD

**Issue by alessfg** [nginx/docker-nginx-unprivileged#136]
### Is your feature request related to a problem? Please describe

CVEs are routinely posted for these images. Most of them do not affect NGINX directly, but that's not always the case.

### Describe the solution you'd like

We should scan for CVEs on a daily basis and flag any relevant CVEs as critical (CVEs with a critical severity that directly impact NGINX or a package used by NGINX). Should any critical CVEs be flagged, we should check if a fix for the CVEs is available, and if so, immediately rebuild the relevant images.

### Additional context

As of today, Docker builds are cached using the GitHub Actions cache. The base Alpine/Debian images are not necessarily rebuilt/pushed when a new CVE is found and fixed, so we might need to wipe the GitHub Actions cache before rebuilding any relevant images. See #137 for tracking info.

```[tasklist]
### Tasks
- [ ] Implement CVE scanner 
- [ ] Configure CVE scanner alerts
- [ ] Rebuild images on critical alerts **if** there is a fix available for the CVE
```

**Comment by K2ouMais** [comment]
Is there a way to update openssl? It seems I cant update it as the "nginx" user?

![image](https://github.com/nginxinc/docker-nginx-unprivileged/assets/52510455/bdcd895f-a8d0-4b99-af6a-78101ddb103c)

**Comment by alessfg** [comment]
Did you pull the latest image released this AM? The issue should have been fixed.

Also, for future reference, I would appreciate if you open a new issue if you think there's a security issue (assuming it qualifies per the [Security](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/.github/SECURITY.md) guidelines)  😄

**Comment by alessfg** [comment]
See #174 for my answer 🙂
